name: Build Lint Test

on:
  push:
    branches:
      - '**'
      - '!changelog'
      - '!changelog/*'
      - '!docs'
      - '!docs/*'

jobs:
  build:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build Test
        run: npm run build-test

  lint:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Do coverage test
        run: npm run test-full
