name: Test features

on:
  push:
    branches:
      - '**'
      - '!changelog'
      - '!changelog/*'
      - '!docs'
      - '!docs/*'

jobs:
  features:
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['8.3.0', 9, 10, 12, 14, 16]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build test
        run: pnpm run build-test

      - name: Setup Node.js environment for test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Check node version
        run: node --version

      - name: Run test 'basic'
        run: node dist/test/features/basic.js

      - name: Run test 'benchmarking-settings'
        run: node dist/test/features/benchmarking-settings.js

      - name: Run test 'columns'
        run: node dist/test/features/columns.js

      - name: Run test 'parameter'
        run: node dist/test/features/parameter.js

      - name: Run test 'setup-cleanup'
        run: node dist/test/features/setup-cleanup.js

      - name: Run test 'validation'
        run: node dist/test/features/validation.js

      - name: Restore Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
